### ISSUE TITLE
NPE at AbstractPropertyDictionary

### ISSUE THREAD

**Issue by umjammer** [umjammer/rococoa#16]
```
java.lang.NullPointerException: Cannot invoke "org.rococoa.cocoa.foundation.NSNumber.intValue()" because the return value of "org.rococoa.contrib.AbstractPropertyDictionary.getValueAsType(java.lang.Enum, java.lang.Class)" is null
	at org.rococoa.contrib.AbstractPropertyDictionary.getInt(AbstractPropertyDictionary.java:92)
	at org.rococoa.cocoa.appkit.NSVoice.getAge(NSVoice.java:130)
```

**Comment by umjammer** [comment]
NSSpeechSynthesizer is deprecated
